### ISSUE TITLE
Npm & yarn error

### ISSUE THREAD

**Issue by shawnrossouw** [younessidbakkasse/workflow#29]
I'm getting an error on both npm and yarn when running "yarn start" and or "npm start"

npm ERR! missing script: start

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/shawn/.npm/_logs/2021-10-03T07_55_25_191Z-debug.log

yarn run error Command "start" not found. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

I followed the installation guide but I'm not sure why this giving an error. Any ideas? Am I missing something?

Thanks

**Comment by younessidbakkasse** [comment]
I woudn't recommend using NPM, use yarn instead ```yarn install```to install all the packages then run ```yarn start```.
