### ISSUE TITLE
Can't Reach the Local Shopify Development Environment on the Safari

### ISSUE THREAD

**Issue by fatihturan** [younessidbakkasse/workflow#44]
When I try to enter `http://127.0.0.1:9292/` URL in the Safari, first it's [showing the password screen](https://share.getcloudapp.com/Z4urJdLp) (because of this is development store and Shopify enforces this) and after entering correct password, Safari [can't open the URL](https://share.getcloudapp.com/llukZjDK). 

I'm using Safari as primary browser and rarely using the Chrome and I think it's related with the SSL thing.

**Comment by younessidbakkasse** [comment]
This is a Shopify CLI issue, I runned into this many times, to check your local development Shopify website on Safari, I usualy use the preview link instead of the localhost url.
